url: "https://developerburakgul.github.io"
include: [".well-known"]

defaults:
  - scope: { path: "templateapp" }
    values:
      layout: applink
      app_id: "TEMPLATEAPP_APP_STORE_ID"
      app_name: "TemplateApp"
  - scope: { path: "tapzero" }
    values:
      layout: applink
      app_id: "6760951806"
      app_name: "TapZero"
